"""Normalization of provider DTOs into repository-ready persistence payloads.

Pure functions -- no I/O, no side effects, mirroring market_data/financials/
corporate_filings' normalization.py separation. The one thing this module
does that its siblings don't is heading/section detection -- still entirely
mechanical (string-shape heuristics: numbering patterns, ALL CAPS, Title
Case, line length, trailing punctuation), never inferred or generated by a
model. This is what "deterministic document extraction" means for this
sprint: the same input document produces byte-identical output every time.
"""

import re
from dataclasses import dataclass

from nivesh.document_intelligence.providers.base import ProviderExtractionResult

_HEADING_MAX_CHARS = 120
_HEADING_MAX_WORDS = 12
_TITLE_CASE_HEADING_MAX_WORDS = 8
_SENTENCE_ENDING_CHARS = (".", ",", ";")
_NUMBERED_HEADING_PATTERN = re.compile(r"^(\d+(?:\.\d+)*)[.)]?\s+\S")

_DEFAULT_HEADING = "Document"
_DEFAULT_LEVEL = 0


@dataclass(frozen=True)
class NormalizedSection:
    sequence: int
    heading: str
    level: int
    page_number: int
    content: str


@dataclass(frozen=True)
class NormalizedExtraction:
    extracted_text: str
    page_count: int
    section_count: int
    sections: list[NormalizedSection]


def _looks_title_case(line: str) -> bool:
    words = [word for word in line.split() if any(char.isalpha() for char in word)]
    if not words:
        return False
    return all(word[0].isupper() for word in words)


def _is_heading_candidate(line: str) -> bool:
    if not (1 <= len(line) <= _HEADING_MAX_CHARS):
        return False
    if line[-1] in _SENTENCE_ENDING_CHARS:
        return False

    words = line.split()
    if not words or len(words) > _HEADING_MAX_WORDS:
        return False

    if _NUMBERED_HEADING_PATTERN.match(line):
        return True

    letters = [char for char in line if char.isalpha()]
    if not letters:
        return False
    if all(char.isupper() for char in letters):
        return True

    return _looks_title_case(line) and len(words) <= _TITLE_CASE_HEADING_MAX_WORDS


def _heading_level(line: str) -> int:
    match = _NUMBERED_HEADING_PATTERN.match(line)
    if match:
        return match.group(1).count(".") + 1

    letters = [char for char in line if char.isalpha()]
    if letters and all(char.isupper() for char in letters):
        return 1

    return 2


def _build_canonical_text(result: ProviderExtractionResult) -> str:
    parts = [f"--- Page {page.page_number} ---\n{page.text.strip()}" for page in result.pages]
    return "\n\n".join(parts).strip()


def _build_sections(result: ProviderExtractionResult) -> list[NormalizedSection]:
    sections: list[NormalizedSection] = []
    sequence = 0
    heading = _DEFAULT_HEADING
    level = _DEFAULT_LEVEL
    page_number = result.pages[0].page_number if result.pages else 1
    lines: list[str] = []
    is_placeholder = True

    def flush() -> None:
        nonlocal sequence
        if is_placeholder and not lines:
            return
        sections.append(
            NormalizedSection(
                sequence=sequence,
                heading=heading,
                level=level,
                page_number=page_number,
                content="\n".join(lines).strip(),
            )
        )
        sequence += 1

    for page in result.pages:
        for raw_line in page.text.splitlines():
            line = raw_line.strip()
            if not line:
                continue
            if _is_heading_candidate(line):
                flush()
                heading = line
                level = _heading_level(line)
                page_number = page.page_number
                lines = []
                is_placeholder = False
            else:
                lines.append(line)
    flush()

    return sections


def normalize_extraction(result: ProviderExtractionResult) -> NormalizedExtraction:
    sections = _build_sections(result)
    return NormalizedExtraction(
        extracted_text=_build_canonical_text(result),
        page_count=len(result.pages),
        section_count=len(sections),
        sections=sections,
    )
